::msgcat::mcmset de {
"##### File Menu"               "##### Datei Menu"
"File"                          "Datei"
"New"                           "Neu"
"Open..."                       "öffnen..."
"Close"                         "Schliessen"
"Save"                          "Speichern"
"Save as"                       "Speichern unter"
"Exit"                          "Beenden"

"##### Edit Menu"               "##### Bearbeiten Menu"
"Edit"                          "Bearbeiten"
"Cut"                           "Ausschneiden"
"Copy"                          "Kopieren"
"Paste"                         "Einfügen"

"##### Planform Menu"           "##### Planform Menu"
"Planform"                      "Planform-d"
"Leading edge"                  "Eintrittskante"
"Trailing edge"                 "Austrittskante"
"Cells number and distribution" "Cells number and distribution-d"
"Geometry matrix inspection"    "Geometry matrix inspection-d"

"##### Vault Menu"              "##### Vault-d Menu"
"Vault"                         "Vault-d"

"##### Airfoils Menu"           "##### Airfoils-d Menu"
"Airfoils"                      "Airfoils-d"

"##### Calage Menu"             "##### Calage-d Menu"
"Calage"                        "Calage-d"

"##### Skin Menu"               "##### Skin-d Menu"
"Skin"                          "Skin-d"

"##### VH-ribs Menu"            "##### VH-ribs-d Menu"
"VH-ribs"                       "VH-ribs-d"

"##### Lines Menu"              "##### Leinen Menu"
"Lines"                         "Leinen"
"Basic"                         "Grundlagen"
"Lines A"                       "A-Leinen"
"Lines B"                       "B-Leinen"
"Lines C"                       "C-Leinen"
"Lines D"                       "D-Leinen"
"Lines E"                       "E-Leinen"
"Brakes"                        "Bremsleinen"

"##### Colors Menu"             "##### Farben Menu"
"Colors"                        "Farben"

"##### Parameters Menu"         "##### Parameter Menu"
"Parameters"                    "Parameter"

"##### DXF Menu"                "##### DXF Menu"
"DXF"                           "DXF"

"##### txt Menu"                "##### txt Menu"
"txt"                           "txt"

"##### Settings Menu"           "##### Einstellungen Menu"
"Settings"                      "Einstellungen"
"Language"                      "Sprache"

"##### Help Menu"               "##### Hilfe Menu"
"Help"                          "Hilfe"
"Version"                       "Version"
"About"                         "über"

"lbl_LangChanged"               "Sprache geändert"
"txt_PlsRestart"                "Bitte starten Sie neu um die änderung zu übernehmen."
}
