::msgcat::mcmset de {
"##### File Menu"               "##### Datei Menu"
"File"                          "Datei"
"New"                           "Neu"
"Open..."                       "öffnen..."
"Close"                         "Schliessen"
"Save"                          "Speichern"
"Save as"                       "Speichern unter"
"Exit"                          "Beenden"

"##### Edit Menu"               "##### Bearbeiten Menu"
"Edit"                          "Bearbeiten"
"Cut"                           "Ausschneiden"
"Copy"                          "Kopieren"
"Paste"                         "Einfügen"

"##### Planform Menu"           "##### Grundriss Menu"
"Planform"                      "Grundriss"
"Leading edge"                  "Eintrittskante"
"Trailing edge"                 "Austrittskante"
"Cells number and distribution" "Zellenanzahl und Verteilung"
"Geometry matrix inspection"    "Geometrie Matrix"

"##### Vault Menu"              "##### Vault Menu"
"Vault"                         "Vault"

"##### Airfoils Menu"           "##### Airfoils Menu"
"Airfoils"                      "Airfoils"

"##### Calage Menu"             "##### Calage Menu"
"Calage"                        "Calage"

"##### Skin Menu"               "##### Skin Menu"
"Skin"                          "Skin"

"##### VH-ribs Menu"            "##### VH-ribs Menu"
"VH-ribs"                       "VH-ribs"

"##### Lines Menu"              "##### Leinen Menu"
"Lines"                         "Leinen"
"Basic"                         "Grundlagen"
"Lines A"                       "A-Leinen"
"Lines B"                       "B-Leinen"
"Lines C"                       "C-Leinen"
"Lines D"                       "D-Leinen"
"Lines E"                       "E-Leinen"
"Brakes"                        "Bremsleinen"

"##### Colors Menu"             "##### Farben Menu"
"Colors"                        "Farben"

"##### Parameters Menu"         "##### Parameter Menu"
"Parameters"                    "Parameter"

"##### DXF Menu"                "##### DXF Menu"
"DXF"                           "DXF"

"##### txt Menu"                "##### txt Menu"
"txt"                           "txt"

"##### Run Menu"           		"##### Ausführen Menu"
"Run"							"Ausführen"
"pre-Processor"					"pre-Prozessor"
"Both"							"Beide"


"##### Settings Menu"           "##### Einstellungen Menu"
"Settings"                      "Einstellungen"
"Language"                      "Sprache"
"pre-Processor Directory"		"pre-Prozessor Installationsverzeichnis"
"lep Directory"					"lep Installationsverzeichnis"

"##### Help Menu"               "##### Hilfe Menu"
"Help"                          "Hilfe"
"Version"                       "Version"
"About"                         "über"

"lbl_LangChanged"               "Sprache geändert"

"title_SelectPreProcDirectory"  "pre-Prozessor Installationsverzeichnis auswählen"
"title_SelectLepDirectory" 		"lep Installationsverzeichnis auswählen"

"txt_PlsRestart"                "Bitte starten Sie neu um die änderung zu übernehmen."
}
