::msgcat::mcmset en {
"##### File Menu"       "##### File Menu"
"File"                  "File"
"New"                   "New"
"Open..."               "Open"
"Close"                 "Close"
"Save"                  "Save"
"Save as"               "Save as"
"Exit"                  "Exit"

"##### Edit Menu"       "##### Edit Menu"
"Edit"                  "Edit"
"Cut"                   "Cut"
"Copy"                  "Copy"
"Paste"                 "Paste"

"##### Planform Menu"   "##### Planform Menu"
"Planform"              "Planform"


"lbl_LangChanged"       "Language selection changed"

"title_SelectPreProcDirectory" "Select pre-Processor installation directory"
"title_SelectLepDirectory" "Select lep installation directory"

"txt_PlsRestart"        "Please restart the application to update the user interface."

"wingNamePreProc"       "Wing name"
"a1LE"                  "a axis ellipse"
"b1LE"                  "a"
"x1LE"                  "b"
"xmLE"                  "c"
"c0LE"                  "d"
"a1TE"                  "e"
"b1TE"                  "f"
"x1TE"                  "g"
"xmTE"                  "h"
"c0TE"                  "i"
"y0TE"                  "k"
"a1Vault"               "l"
"b1Vault"               "m"
"x1Vault"               "n"
"xmVault"               "o"
"radVault"              "p"
"angVault"              "q"
"cellDistrCoeff"        "0.0 ... 1.0"
"numCellsPreProc"       "s"
}
