::msgcat::mcmset en {
"##### File Menu"       "##### File Menu"
"File"                  "File"
"New"                   "New"
"Open..."               "Open"
"Close"                 "Close"
"Save"                  "Save"
"Save as"               "Save as"
"Exit"                  "Exit"

"##### Edit Menu"       "##### Edit Menu"
"Edit"                  "Edit"
"Cut"                   "Cut"
"Copy"                  "Copy"
"Paste"                 "Paste"

"##### Planform Menu"   "##### Planform Menu"
"Planform"              "Planform"

"lbl_LangChanged"       "Language selection changed"
"txt_PlsRestart"        "Please restart the application to update the user interface."
}
