::msgcat::mcmset en {
"##### File Menu"       "##### File Menu"
"File"                  "File-e"
"New"                   "New-e"
"Open..."               "Open"
"Close"                 "Close"
"Save"                  "Save"
"Save as"               "Save as"
"Exit"                  "Exit"

"##### Edit Menu"       "##### Edit Menu"
"Edit"                  "Edit"
"Cut"                   "Cut"
"Copy"                  "Copy"
"Paste"                 "Paste"


"lbl_LangChanged"       "Language selection changed"
"txt_PlsRestart"        "Please restart the application to update the user interface."
}
