::msgcat::mcmset ca {
"##### File Menu"               "##### Arxius Menu"
"File"                          "Arxiu"
"New"                           "Nou"
"Open..."                       "Obrir..."
"Close"                         "Tancar"
"Save"                          "Desa"
"Save as"                       "Desa com"
"Exit"                          "Eixir"

"##### Edit Menu"               "##### Edita Menu"
"Edit"                          "Edita"
"Cut"                           "Talla"
"Copy"                          "Copia"
"Paste"                         "Enganxa"

"##### Planform Menu"           "##### Planta Menu"
"Planform"                      "Planta"
"Leading edge"                  "Vora d'atac"
"Trailing edge"                 "Vora de sortida"
"Cells number and distribution" "Cel·les, nombre i distribució"
"Geometry matrix inspection"    "Matriu de geometria"

"##### Vault Menu"              "##### Volta Menu"
"Vault"                         "Volta"

"##### Airfoils Menu"           "##### Perfils Menu"
"Airfoils"                      "Perfils aerodinàmics"
"02. Airfoils"                  "02. Perfils"

"##### Calage Menu"             "##### Calatge Menu"
"Calage"                        "Calatge"

"##### Skin Menu"               "##### Skin Menu"
"Skin"                          "Tensió de vela"

"##### VH-ribs Menu"            "##### VH-ribs Menu"
"VH-ribs"                       "VH-ribs"

"##### Lines Menu"              "##### Línies Menu"
"Lines"                         "Línies"
"Basic"                         "Bàsic"
"Lines A"                       "A-Línies"
"Lines B"                       "B-Línies"
"Lines C"                       "C-Línies"
"Lines D"                       "D-Línies"
"Lines E"                       "E-Línies"
"Brakes"                        "Frens"

"##### Colors Menu"             "##### Colors Menu"
"Colors"                        "Colors"

"##### Parameters Menu"         "##### Paràmetres Menu"
"Parameters"                    "Paràmetres"

"##### DXF Menu"                "##### DXF Menu"
"DXF"                           "DXF"

"##### txt Menu"                "##### txt Menu"
"txt"                           "txt"

"##### Settings Menu"           "##### Ajustaments Menu"
"Settings"                      "Ajustaments"
"Language"                      "Llengua"

"##### Help Menu"               "##### Ajuda Menu"
"Help"                          "Ajuda"
"Version"                       "Versió"
"About"                         "Sobre"

"lbl_LangChanged"               "Canvi de llengua"
"txt_PlsRestart"                "Reinicia per aplicar els canvis"
}
