::msgcat::mcmset de {
"Explanations"                  "Erklärungen"

"##### File Menu"               "##### Datei Menu"
"Exit"                          "Beenden"

"##### Geometry Menu"           "##### Geometrie Menu"
"Geometry"                      "Geometrie"
"Open Geometry..."              "Geometrie öffnen..."
"Edit Geometry"                 "Geometrie editieren"
"Calc Geometry"                 "Geometrie berechnen"
"Save Geometry"                 "Geometrie speichern"
"Save Geometry As"              "Geometrie speichern unter"

"##### Wing Menu"               "##### Flügel Menu"
"Wing"                          "Flügel"
"New Wing"                      "Neuer Flügel"
"Import Wing Geometry"          "Flügel Geometrie importieren"
"Open Wing..."                  "Flügel öffnen..."
"Save Wing"                     "Flügel speichern"
"Save Wing As"                  "Flügel speichern unter"
"Basic Data"                    "Basisdaten"

"##### Edit Menu"               "##### Bearbeiten Menu"
"Edit"                          "Bearbeiten"
"Cut"                           "Ausschneiden"
"Copy"                          "Kopieren"
"Paste"                         "Einfügen"

"##### Planform Menu"           "##### Grundriss Menu"
"Planform"                      "Grundriss"
"Leading edge"                  "Eintrittskante"
"Trailing edge"                 "Austrittskante"
"Cells number and distribution" "Zellenanzahl und Verteilung"
"Geometry matrix inspection"    "Geometrie Matrix"

"##### Vault Menu"              "##### Vault Menu"
"Vault"                         "Vault"

"##### Airfoils Menu"           "##### Airfoils Menu"
"Airfoils"                      "Airfoils"

"##### Calage Menu"             "##### Calage Menu"
"Calage"                        "Calage"

"##### Skin Menu"               "##### Skin Menu"
"Skin"                          "Skin"

"##### VH-ribs Menu"            "##### VH-ribs Menu"
"VH-ribs"                       "VH-ribs"

"##### Lines Menu"              "##### Leinen Menu"
"Lines"                         "Leinen"
"Basic"                         "Grundlagen"
"Lines A"                       "A-Leinen"
"Lines B"                       "B-Leinen"
"Lines C"                       "C-Leinen"
"Lines D"                       "D-Leinen"
"Lines E"                       "E-Leinen"
"Brakes"                        "Bremsleinen"

"##### Colors Menu"             "##### Farben Menu"
"Colors"                        "Farben"

"##### Parameters Menu"         "##### Parameter Menu"
"Parameters"                    "Parameter"

"##### DXF Menu"                "##### DXF Menu"
"DXF"                           "DXF"

"##### txt Menu"                "##### txt Menu"
"txt"                           "txt"

"##### Run Menu"           		"##### Ausführen Menu"
"Run"							"Ausführen"
"pre-Processor"					"pre-Prozessor"
"Both"							"Beide"


"##### Settings Menu"           "##### Einstellungen Menu"
"Settings"                      "Einstellungen"
"Language"                      "Sprache"
"pre-Processor Directory"		"pre-Prozessor Installationsverzeichnis"
"lep Directory"					"lep Installationsverzeichnis"

"##### Help Menu"               "##### Hilfe Menu"
"Help"                          "Hilfe"
"Version"                       "Version"
"About"                         "über"

"lbl_LangChanged"               "Sprache geändert"

"title_SelectPreProcDirectory"  "pre-Prozessor Installationsverzeichnis auswählen"
"title_SelectLepDirectory" 		"lep Installationsverzeichnis auswählen"

"txt_PlsRestart"                "Bitte starten Sie neu um die änderung zu übernehmen."

"##### Main Window"             "##### Haupfenster"
"Tail view"                     "Hinteransicht"
"Top view"                      "Grundriss"
"Side view"                     "Seitenansicht"
"Basic data"                    "Grunddaten"

"Brand Name"                    "Herstellername"
"Wing Name"                     "Flügelname"
"Draw Scale"                    "Zeichnungsmasstab"
"Wing scale"                    "Flügelmasstab"
"Number of Cells"               "Anzahl Zellen"
"Number of Ribs"                "Anzahl Rippen"

"##### Edit Geometry Window"    "##### Fenster Geometrie bearbeiten"
"Edit Geometry data"            "Geometrie bearbeiten"
"Wing name"                     "Flügelname"
"Vault"                         "Krümmung"
"Sin-Cos modif"                 "Sinus-Cosinus Modif"
"Radius/ Angle"                 "Radius/ Winkel"
"Cell distribution"             "Zellenverteilung"
"Cell width proportional to chord"  "Zellenbreite proportional zur Spannweite"
"Explicit width of each cell"       "Feste Zellenbreite"
"Cell distribution coef"            "Zell Verteilungs Koeffizient"
"Number of cells"                   "Anzahl Zellen"

"wingNamePreProc"       "Flügelname"
"a1LE"                  "Ellipse der Eintrittskante"
"b1LE"                  "Flügeltiefe Eintrittskante"
"x1LE"                  "Krümmungsstart Eintrittskante"
"xmLE"                  "Halbe Spannweite Eintrittskante"
"c0LE"                  "Ablenkung Eintrittskante"
"a1TE"                  "Ellipse der Austrittskante"
"b1TE"                  "Flügeltiefe Austrittskante"
"x1TE"                  "Krümmungsstart Austrittskante"
"xmTE"                  "Halbe Spannweite Austrittskante"
"c0TE"                  "Ablenkung Austrittskante"
"y0TE"                  "Flügeltiefenreduktion Austrittskante"
"a1Vault"               "Flügelhöhe"
"b1Vault"               "Halbe Flügelspannweite"
"x1Vault"               "Krümmungsstart Flügel"
"xmVault"               "Ablenkung Flügel"
"radVault"              "Radius"
"angVault"              "Winkel"
"cellDistrCoeff"        "0.0 (proportional)... 1.0 (gleiche Breite)"
"numCellsPreProc"       "Totale Anzahl Zellen"

"txt_writePreProcInputData" "Schreibe Daten für Geometrie Prozessor..."
"txt_findPreProcOutputFilesIn" "Berechnete Daten sind im ....\\lepg\\process Verzeichnis"

"##### Basic Data Window"    "##### Fenster Basisdaten"
"Wing Basic Data"       "Flügel Basisdaten"
"Brand Name"            "Name des Herstellers"
"Wing Name"             "Name des Flügels"
"Draw Scale"            "Zeichnungsmasstab"
"Wing Scale"            "Flügelmasstab"

"brandName"             "Herstellername"
"wingName"              "Flügelname"
"drawScale"             "Zeichnungsmasstab"
"wingScale"             "Flügelmasstab"
}
