::msgcat::mcmset en {
"##### File Menu"       "##### File Menu"
"File"                  "File"
"New"                   "New"
"Open..."               "Open"
"Close"                 "Close"
"Save"                  "Save"
"Save as"               "Save as"
"Exit"                  "Exit"

"##### Edit Menu"       "##### Edit Menu"
"Edit"                  "Edit"
"Cut"                   "Cut"
"Copy"                  "Copy"
"Paste"                 "Paste"

"##### Planform Menu"   "##### Planform Menu"
"Planform"              "Planform"


"lbl_LangChanged"       "Language selection changed"

"title_SelectPreProcDirectory" "Select pre-Processor installation directory"
"title_SelectLepDirectory" "Select lep installation directory"

"txt_PlsRestart"        "Please restart the application to update the user interface."

"wingNamePreProc"       "Wing name"
"a1LE"                  "Leading edge ellipse"
"b1LE"                  "Wing depth leading edge section"
"x1LE"                  "Curvature start leading edge"
"xmLE"                  "Leading edge half span"
"c0LE"                  "Leading edge deflection"
"a1TE"                  "Trailing edge ellipse"
"b1TE"                  "Wing depth trailing edge section"
"x1TE"                  "Curvature start trailing edge"
"xmTE"                  "Trailing edge half span"
"c0TE"                  "Trailing edge deflection"
"y0TE"                  "Trailing edge wing deep reduction"
"a1Vault"               "Wing height"
"b1Vault"               "Wing width"
"x1Vault"               "Wing curvature start"
"xmVault"               "Wing span deflection"
"radVault"              "Radius"
"angVault"              "Angle"
"cellDistrCoeff"        "0.0 (proportional)... 1.0 (uniform)"
"numCellsPreProc"       "Total number of cells"

"txt_writePreProcInputData" "Writing input data for processor..."
"txt_findPreProcOutputFilesIn" "Output files can be found in ....\\lepg\\process directory"
}
