::msgcat::mcmset pl {
"##### File Menu"               "##### Plik Menu"
"File"                          "Plik"
"New"                           "Nowy"
"Open..."                       "Otwórz..."
"Close"                         "Zamknij"
"Save"                          "Zapisz"
"Save as"                       "Zapisz jako"
"Exit"                          "Zakoñcz"

"##### Edit Menu"               "##### Edycja Menu"
"Edit"                          "Edytuj"
"Cut"                           "Wytnik"
"Copy"                          "Kopiuj"
"Paste"                         "Wklej"

"Draw"                          "Remis"
"Wing type"                     "Typ skrzyd¿a"
"Wing surface"                  "Powierzchnia skrzyde¿"
"Wing span"                     "Rozpi¿to¿¿"
"Wing aspect ratio"             "Wspó¿czynnik proporcji"
"Run"                           "Biega¿"

"##### Planform Menu"           "##### Kszta³t Menu"
"Planform"                      "Kszta³t"
"Leading edge"                  "Krawêd natarcia"
"Trailing edge"                 "Krawêd sp³ywu"
"Cells number and distribution" "Numeracja komór i rozk³ad"
"Geometry matrix inspection"    "Geometria Macierz"

"##### Vault Menu"              "##### Ugiêcie Menu"
"Vault"                         "Ugiêcie"

"##### Airfoils Menu"           "##### Profil Menu"
"Airfoils"                      "Profil aerodynamiczny"

"##### Calage Menu"             "##### Wywa¿enie Menu"
"Calage"                        "Wywa¿enie"

"##### Skin Menu"               "##### Powierzchnia Menu"
"Skin"                          "Powierzchnia"

"##### VH-ribs Menu"            "##### VH-¿ebra Menu"
"VH-ribs"                       "VH-¿ebra"

"##### Lines Menu"              "##### Olinowanie Menu"
"Lines"                         "Olinowanie"
"Basic"                         "Podstawa"
"Lines A"                       "Liny rzêdu A"
"Lines B"                       "Liny rzêdu B"
"Lines C"                       "Liny rzêdu C"
"Lines D"                       "Liny rzêdu D"
"Lines E"                       "Liny rzêdu E"
"Brakes"                        "Hamulce"

"##### Colors Menu"             "##### Kolor Menu"
"Colors"                        "Kolor"

"##### Parameters Menu"         "##### Parametry Menu"
"Parameters"                    "Parametry"

"##### DXF Menu"                "##### DXF Menu"
"DXF"                           "DXF"

"##### txt Menu"                "##### txt Menu"
"txt"                           "txt"

"##### Settings Menu"           "##### Ustawienia Menu"
"Settings"                      "Ustawienia"
"Language"                      "Jêzyk"

"##### Help Menu"               "##### Pomoc Menu"
"Help"                          "Pomoc"
"Version"                       "Versja"
"About"                         "O mnie"
"Apply"                          "Zastosowa¿"
"OK"                            "Dobrze!"
"Cancel"                        "Anuluj"

"lbl_LangChanged"               "Zmiana jêzyka"
"txt_PlsRestart"                "Proszê ponownie uruchomiæ"
}
